// <auto-generated />
using System;
using AppDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppDB.Migrations
{
    [DbContext(typeof(computerContext))]
    partial class computerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AppDB.Models.Laptop", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("code")
                        .UseIdentityColumn();

                    b.Property<float>("Hd")
                        .HasColumnType("real")
                        .HasColumnName("hd");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<short>("Ram")
                        .HasColumnType("smallint")
                        .HasColumnName("ram");

                    b.Property<byte>("Screen")
                        .HasColumnType("tinyint")
                        .HasColumnName("screen");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint")
                        .HasColumnName("speed");

                    b.HasKey("Code");

                    b.HasIndex("Model");

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("AppDB.Models.Pc", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("code")
                        .UseIdentityColumn();

                    b.Property<string>("Cd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cd");

                    b.Property<float>("Hd")
                        .HasColumnType("real")
                        .HasColumnName("hd");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<short>("Ram")
                        .HasColumnType("smallint")
                        .HasColumnName("ram");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint")
                        .HasColumnName("speed");

                    b.HasKey("Code");

                    b.HasIndex("Model");

                    b.ToTable("PC");
                });

            modelBuilder.Entity("AppDB.Models.Printer", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("code")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("color");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Code");

                    b.HasIndex("Model");

                    b.ToTable("Printer");
                });

            modelBuilder.Entity("AppDB.Models.Product", b =>
                {
                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("maker");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Model");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AppDB.Models.Laptop", b =>
                {
                    b.HasOne("AppDB.Models.Product", "ModelNavigation")
                        .WithMany("Laptops")
                        .HasForeignKey("Model")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelNavigation");
                });

            modelBuilder.Entity("AppDB.Models.Pc", b =>
                {
                    b.HasOne("AppDB.Models.Product", "ModelNavigation")
                        .WithMany("Pcs")
                        .HasForeignKey("Model")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelNavigation");
                });

            modelBuilder.Entity("AppDB.Models.Printer", b =>
                {
                    b.HasOne("AppDB.Models.Product", "ModelNavigation")
                        .WithMany("Printers")
                        .HasForeignKey("Model")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelNavigation");
                });

            modelBuilder.Entity("AppDB.Models.Product", b =>
                {
                    b.Navigation("Laptops");

                    b.Navigation("Pcs");

                    b.Navigation("Printers");
                });
#pragma warning restore 612, 618
        }
    }
}
